### ISSUE TITLE
C# SDK Testsuite to avoid having to spin up BitCraft to test basic functionality

### ISSUE THREAD

**Issue by cloutiertyler** [clockworklabs/spacetimedb-csharp-sdk#105]
Highest value tests:

- State diff tests: Should process dummy transactions and make sure that the state of the table is correct at the end (various combos of inserts and deletes)
- Call back tests: Should process dummy transactions and ensure that the right call backs are called
- Make sure that updates are processed correctly based on inserts, deletes, and primary keys

Requires SpacetimeDB is running
- Test for one off queries to ensure that it's still working

**Comment by RReverser** [comment]
Seems like a duplicate of https://github.com/clockworklabs/SpacetimeDB/issues/1376 which I resolved couple of weeks ago. 

We already have all of listed tests except one-off query tests.
