### ISSUE TITLE
Unable to Install spacetimedbsdk Package Using .NET CLI in Windows Powershell

### ISSUE THREAD

**Issue by blitzfall** [clockworklabs/spacetimedb-csharp-sdk#50]
**Description:**
When attempting to install the spacetimedbsdk package using the .NET CLI in Windows Powershell, I encountered an error indicating that there are no available versions for the package. The documented command to install the package did not work as expected.

**Steps to Reproduce:**
1. Open Windows Powershell.
2. Navigate to the project directory: (In my case: C:\Users\blitz\Desktop\spacetime-test\client)
3. Run the command: dotnet add package spacetimedbsdk

**Expected Result:**
The spacetimedbsdk package should be added to the project without any issues.

**Actual Result:**
Received the following error:
```error: There are no versions available for the package 'spacetimedbsdk'.```

**Additional Information:**
.NET CLI Version: Version 7.0.201 (_dotnet --info_ > .NET SDK)
Operating System: Windows 11
Logs:
```
(base) PS C:\Users\blitz\Desktop\spacetime-test\client> dotnet add package spacetimedbsdk
Determining projects to restore...
Writing C:\Users\blitz\AppData\Local\Temp\tmpE925.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : Adding PackageReference for package 'spacetimedbsdk' into project 'C:\Users\blitz\Desktop\spacetime-test\client\client.csproj'.
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/spacetimedbsdk/index.json
info :   CACHE https://api.nuget.org/v3/registration5-gz-semver2/spacetimedbsdk/index.json
error: There are no versions available for the package 'spacetimedbsdk'.
```

**Comment by jdetter** [comment]
Looking into this now, thank you for the bug report 👍

**Comment by dbrinkmanncw** [comment]
https://github.com/clockworklabs/spacetime-web/pull/257

**Comment by jdetter** [comment]
This is resolved now 👍
