### ISSUE TITLE
Unique types should autogenerate as `FindBy` instead of `FilterBy`

### ISSUE THREAD

**Issue by jdetter** [clockworklabs/spacetimedb-csharp-sdk#69]

**Comment by cloutiertyler** [comment]
Note this applies to Rust modules as well and requires a PR against the BitCraft module to fix the incompatibility.

**Comment by RReverser** [comment]
> Note this applies to Rust modules as well and requires a PR against the BitCraft module to fix the incompatibility.

We probably should have a separate issue for that in Rust SDK or SpacetimeDB, as this is a repo of C# SDK specifically.
